package ORM;
// Generated 2022-01-17 22:02:44 by Hibernate Tools 4.3.1



/**
 * Wcy19kc1s1DudkaProjekt generated by hbm2java
 */
public class Wcy19kc1s1DudkaProjekt  implements java.io.Serializable {


     private int id;
     private String hash;
     static int nextId = 0;

    public Wcy19kc1s1DudkaProjekt() {
    }

	
    public Wcy19kc1s1DudkaProjekt(String hash) {
        this.hash = hash;
        this.id = nextId++;
    }
    public Wcy19kc1s1DudkaProjekt(int id, String hash) {
       this.id = id;
       this.hash = hash;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }




}


