package Trwalosc;
// Generated 2021-11-15 20:13:17 by Hibernate Tools 4.3.1



/**
 * Shoes generated by hbm2java
 */
public class Shoes  implements java.io.Serializable {


     private int shoeId;
     private String name;
     private String brand;
     private String type;
     private String color;
     private Boolean madeOfLeather;
     private Boolean hasLaces;

    public Shoes() {
    }

	
    public Shoes(int shoeId) {
        this.shoeId = shoeId;
    }
    public Shoes(int shoeId, String name, String brand, String type, String color, Boolean madeOfLeather, Boolean hasLaces) {
       this.shoeId = shoeId;
       this.name = name;
       this.brand = brand;
       this.type = type;
       this.color = color;
       this.madeOfLeather = madeOfLeather;
       this.hasLaces = hasLaces;
    }
   
    public int getShoeId() {
        return this.shoeId;
    }
    
    public void setShoeId(int shoeId) {
        this.shoeId = shoeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Boolean getMadeOfLeather() {
        return this.madeOfLeather;
    }
    
    public void setMadeOfLeather(Boolean madeOfLeather) {
        this.madeOfLeather = madeOfLeather;
    }
    public Boolean getHasLaces() {
        return this.hasLaces;
    }
    
    public void setHasLaces(Boolean hasLaces) {
        this.hasLaces = hasLaces;
    }




}


